# Generated by Django 3.2.4 on 2021-10-26 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_auto_20211015_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Cleanser', 'Cleanser'), ('Toner', 'Toner'), ('Moisturizer', 'Moisturizer'), ('Essence', 'Essence'), ('Sunscreen', 'Sunscreen'), ('Exfoliation', 'Exfoliation'), ('Serum', 'Serum'), ('Cleansing Oil', 'Cleansing Oil')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
